version: '3'

services:
  postgresql:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_USER=rawan
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    depends_on:
      - postgresql
    environment:
      - POSTGRES_USER=rawan
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=mydatabase
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
    ports:
<<<<<<< HEAD
      - "8081:8080"  # Change the port mapping to 8090:8080
=======
      - "8081:8080"
>>>>>>> 289d3938c4a81706acdf3655be05bca9a3c18ccf

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres-data:

networks:
  default:
    driver: bridge
